export const READING_STATUS = {
  READING: 'Em leitura',
  ON_HOLD: 'Pausado',
  FINISHED: 'Concluído',
};

export const LITERARY_GENRE_LABELS = {
  ROMANCE: 'Romance',
  SCIENCE_FICTION: 'Ficção Científica',
  ADVENTURE: 'Aventura',
  PHILOSOPHY: 'Filosofia',
  DRAMA: 'Drama',
  RELIGIOUS: 'Religião',
  MYSTERY: 'Mistério',
  HORROR: 'Terror',
  HISTORY: 'História',
  BIOGRAPHY: 'Biografia',
  FANTASY: 'Fantasia',
  THRILLER: 'Suspense',
  HUMOR: 'Humor',
  CHILDRENS: 'Infantil',
  YOUNG_ADULT: 'Jovem Adulto',
  POETRY: 'Poesia',
  ART_AND_DESIGN: 'Arte e Design',
  POLITICS: 'Política',
  ECONOMICS: 'Economia',
  'SELF-HELP': 'Auto Ajuda',
  CRIME: 'Crime',
  DYSTOPIAN: 'Distopia',
  WESTERN: 'Faroeste',
  GOTHIC: 'Gótico',
  EROTIC: 'Erótico',
  CYBERPUNK: 'Cyberpunk',
  STEAMPUNK: 'Steampunk',
  COOKING: 'Culinária',
  TRAVEL: 'Viagem',
  SPORTS: 'Esportes',
  FAIRYTALE: 'Conto de Fadas',
  OTHER: 'Outro',

  'JUVENILE FICTION': 'Ficção Juvenil',
  FINANCE: 'Finanças',
  'PORTUGUESE LITERATURE': 'Literatura Portuguesa',
  FICTION: 'Ficção',
  PSYCHOLOGY: 'Psicologia',
  'BIOGRAPHY & AUTOBIOGRAPHY': 'Biografia',
  ART: 'Arte',
};

export const LITERARY_GENRE_OPTIONS = [
  'ADVENTURE',
  'ART',
  'ART_AND_DESIGN',
  'BIOGRAPHY',
  'BIOGRAPHY & AUTOBIOGRAPHY',
  'CHILDRENS',
  'COOKING',
  'CRIME',
  'CYBERPUNK',
  'DRAMA',
  'DYSTOPIAN',
  'ECONOMICS',
  'EROTIC',
  'FAIRYTALE',
  'FANTASY',
  'FICTION',
  'FINANCE',
  'GOTHIC',
  'HISTORY',
  'HORROR',
  'HUMOR',
  'JUVENILE FICTION',
  'MYSTERY',
  'PHILOSOPHY',
  'POETRY',
  'POLITICS',
  'PORTUGUESE LITERATURE',
  'PSYCHOLOGY',
  'RELIGIOUS',
  'ROMANCE',
  'SELF-HELP',
  'SCIENCE_FICTION',
  'SPORTS',
  'STEAMPUNK',
  'THRILLER',
  'TRAVEL',
  'WESTERN',
  'YOUNG_ADULT',
  'OTHER',
];
