import { TLiteraryGenre } from '../@types/Book';

export const READING_STATUS = {
  READING: 'Em leitura',
  ON_HOLD: 'Pausado',
  FINISHED: 'Concluído',
};

export const LITERARY_GENRE_LABELS = {
  ROMANCE: 'Romance',
  SCIENCE_FICTION: 'Ficção Científica',
  ADVENTURE: 'Aventura',
  PHILOSOPHY: 'Filosofia',
  DRAMA: 'Drama',
  RELIGIOUS: 'Religião',
  MYSTERY: 'Mistério',
  HORROR: 'Terror',
  BIOGRAPHY: 'Biografia',
  HISTORICAL: 'História',
  FANTASY: 'Fantasia',
  THRILLER: 'Suspense',
  HUMOR: 'Humor',
  CHILDRENS: 'Infantil',
  YOUNG_ADULT: 'Jovem Adulto',
  POETRY: 'Poesia',
  ART_AND_DESIGN: 'Arte e Design',
  POLITICS: 'Política',
  ECONOMICS: 'Economia',
  SELF_HELP: 'Autoajuda',
  CRIME: 'Crime',
  DYSTOPIAN: 'Distopia',
  WESTERN: 'Faroeste',
  GOTHIC: 'Gótico',
  EROTIC: 'Erótico',
  CYBERPUNK: 'Cyberpunk',
  STEAMPUNK: 'Steampunk',
  COOKING: 'Culinária',
  TRAVEL: 'Viagem',
  SPORTS: 'Esportes',
  FAIRYTALE: 'Conto de Fadas',
  OTHER: 'Outro',
};

export const LITERARY_GENRE_OPTIONS: TLiteraryGenre[] = [
  'ROMANCE',
  'SCIENCE_FICTION',
  'ADVENTURE',
  'PHILOSOPHY',
  'DRAMA',
  'RELIGIOUS',
  'MYSTERY',
  'HORROR',
  'BIOGRAPHY',
  'HISTORICAL',
  'FANTASY',
  'THRILLER',
  'HUMOR',
  'CHILDRENS',
  'YOUNG_ADULT',
  'ART_AND_DESIGN',
  'POETRY',
  'POLITICS',
  'ECONOMICS',
  'SELF_HELP',
  'CRIME',
  'DYSTOPIAN',
  'WESTERN',
  'GOTHIC',
  'EROTIC',
  'CYBERPUNK',
  'STEAMPUNK',
  'COOKING',
  'TRAVEL',
  'SPORTS',
  'FAIRYTALE',
  'OTHER',
];
