export const BOOK_LITERARY_GENRE = {
  ROMANCE: 'Romance',
  SCIENCE_FICTION: 'Ficção Científica',
  ADVENTURE: 'Aventura',
  PHILOSOPHY: 'Filosofia',
  DRAMA: 'Drama',
  RELIGIOUS: 'Religião',
  MYSTERY: 'Mistério',
  HORROR: 'Terror',
  BIOGRAPHY: 'Biografia',
  HISTORICAL: 'História',
  FANTASY: 'Fantasia',
  THRILLER: 'Suspense',
  HUMOR: 'Humor',
  CHILDRENS: 'Infantil',
  YOUNG_ADULT: 'Jovem Adulto',
  POETRY: 'Poesia',
  ART_AND_DESIGN: 'Arte e Design',
  POLITICS: 'Política',
  ECONOMICS: 'Economia',
  SELF_HELP: 'Autoajuda',
  CRIME: 'Crime',
  DYSTOPIAN: 'Distopia',
  WESTERN: 'Faroeste',
  GOTHIC: 'Gótico',
  EROTIC: 'Erótico',
  CYBERPUNK: 'Cyberpunk',
  STEAMPUNK: 'Steampunk',
  COOKING: 'Culinária',
  TRAVEL: 'Viagem',
  SPORTS: 'Esportes',
  FAIRYTALE: 'Conto de Fadas',
  OTHER: 'Outro',
};
